<?php

use Illuminate\Database\Seeder;

class ShopsTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('shops')->insert([
            [
                'name' => 'shop1',
                'phone_number' => '11111111111',
                'fax_number' => '11111111112',
                'postal_code' => '111-1111',
                'address' => '山形県酒田市本町3-804-10',
                'opening_hours' => '10:00～20:00',
                'holiday' => '火曜日',
                'image_path' => 'shop1.png',
                'map_image_path' => 'map1.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'shop2',
                'phone_number' => '22222222222',
                'fax_number' => '22222222223',
                'postal_code' => '222-2222',
                'address' => '愛知県豊田市汐見町3-649-13',
                'opening_hours' => '10:00～21:00',
                'holiday' => '月曜日',
                'image_path' => 'shop2.png',
                'map_image_path' => '',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'shop3',
                'phone_number' => '3333333333',
                'fax_number' => '33333333334',
                'postal_code' => '333-3333',
                'address' => '和歌山県東牟婁郡那智勝浦町下里827-19',
                'opening_hours' => '11:00～21:00',
                'holiday' => '月曜日',
                'image_path' => 'shop3.png',
                'map_image_path' => '',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'shop4',
                'phone_number' => '44444444444',
                'fax_number' => '44444444445',
                'postal_code' => '444-4444',
                'address' => '石川県小松市大領町264-20',
                'opening_hours' => '11:00～21:30',
                'holiday' => '月曜日・水曜日',
                'image_path' => 'shop4.png',
                'map_image_path' => '',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'shop5',
                'phone_number' => '55555555555',
                'fax_number' => '55555555556',
                'postal_code' => '555-5555',
                'address' => '静岡県掛川市平島78-14',
                'opening_hours' => '11:00～22:00',
                'holiday' => '金曜日',
                'image_path' => 'shop5.png',
                'map_image_path' => '',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'shop6',
                'phone_number' => '66666666666',
                'fax_number' => '66666666667',
                'postal_code' => '666-6666',
                'address' => '静岡県袋井市松原524-12',
                'opening_hours' => '10:00～22:00',
                'holiday' => '金曜日',
                'image_path' => 'shop6.png',
                'map_image_path' => '',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'shop7',
                'phone_number' => '77777777777',
                'fax_number' => '77777777778',
                'postal_code' => '777-7777',
                'address' => '山形県天童市大町273-7',
                'opening_hours' => '9:00～21:00',
                'holiday' => '水曜日',
                'image_path' => 'shop7.png',
                'map_image_path' => '',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'shop8',
                'phone_number' => '88888888888',
                'fax_number' => '88888888889',
                'postal_code' => '888-8888',
                'address' => '長野県上水内郡飯綱町川上688-15',
                'opening_hours' => '9:30～20:30',
                'holiday' => '火曜日',
                'image_path' => 'shop8.png',
                'map_image_path' => '',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'shop9',
                'phone_number' => '99999999999',
                'fax_number' => '99999999910',
                'postal_code' => '999-9999',
                'address' => '岐阜県土岐市肥田町浅野100-6',
                'opening_hours' => '10:00～22:00',
                'holiday' => '木曜日',
                'image_path' => 'shop9.png',
                'map_image_path' => '',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'shop10',
                'phone_number' => '10101010101',
                'fax_number' => '10101010111',
                'postal_code' => '101-0101',
                'address' => '大阪府大阪市東淀川区南江口2-136-15',
                'opening_hours' => '12:00～22:00',
                'holiday' => '月曜日・木曜日',
                'image_path' => 'shop10.png',
                'map_image_path' => '',
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);
    }
}
