<?php

use Illuminate\Database\Seeder;

class TravelTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('travel')->insert([
            [
                'application_date' => '2022-01-15',
                'departure_date' => '2022-03-15',
                'day' => '1泊2日',
                'people' => 3,
                'region_id' => 1,
                'cost' => 100000,
                'subsidy' => 10000,
                'coupon' => 5,
                'customer_id' => 1,
                'created_at' =>  now(),
                'updated_at' => now(),
            ],
            [
                'application_date' => '2022-02-01',
                'departure_date' => '2022-02-25',
                'day' => '2泊3日',
                'people' => 1,
                'region_id' => 2,
                'cost' => 80000,
                'subsidy' => 5000,
                'coupon' => 2,
                'customer_id' => 2,
                'created_at' =>  now(),
                'updated_at' => now(),
            ],
            [
                'application_date' => '2021-12-01',
                'departure_date' => '2022-01-05',
                'day' => '1泊2日',
                'people' => 2,
                'region_id' => 3,
                'cost' => 120000,
                'subsidy' => 16000,
                'coupon' => 7,
                'customer_id' => 3,
                'created_at' =>  now(),
                'updated_at' => now(),
            ],
            [
                'application_date' => '2022-05-01',
                'departure_date' => '2022-05-27',
                'day' => '3泊4日',
                'people' => 7,
                'region_id' => 4,
                'cost' => 200000,
                'subsidy' => 50000,
                'coupon' => 10,
                'customer_id' => 4,
                'created_at' =>  now(),
                'updated_at' => now(),
            ],
            [
                'application_date' => '2022-05-15',
                'departure_date' => '2022-09-11',
                'day' => '5泊6日',
                'people' => 10,
                'region_id' => 5,
                'cost' => 250000,
                'subsidy' => 70000,
                'coupon' => 14,
                'customer_id' => 5,
                'created_at' =>  now(),
                'updated_at' => now(),
            ],
            [
                'application_date' => '2022-05-20',
                'departure_date' => '2022-07-25',
                'day' => '1泊2日',
                'people' => 2,
                'region_id' => 6,
                'cost' => 35000,
                'subsidy' => 15000,
                'coupon' => 6,
                'customer_id' => 6,
                'created_at' =>  now(),
                'updated_at' => now(),
            ],
            [
                'application_date' => '2022-01-15',
                'departure_date' => '2022-03-15',
                'day' => '2泊3日',
                'people' => 3,
                'region_id' => 7,
                'cost' => 100000,
                'subsidy' => 10000,
                'coupon' => 5,
                'customer_id' => 7,
                'created_at' =>  now(),
                'updated_at' => now(),
            ],
            [
                'application_date' => '2022-02-15',
                'departure_date' => '2022-08-01',
                'day' => '1泊2日',
                'people' => 2,
                'region_id' => 8,
                'cost' => 18000,
                'subsidy' => 14000,
                'coupon' => 7,
                'customer_id' => 8,
                'created_at' =>  now(),
                'updated_at' => now(),
            ],
            [
                'application_date' => '2021-11-20',
                'departure_date' => '2022-01-15',
                'day' => '3泊4日',
                'people' => 4,
                'region_id' => 9,
                'cost' => 100000,
                'subsidy' => 50000,
                'coupon' => 16,
                'customer_id' => 9,
                'created_at' =>  now(),
                'updated_at' => now(),
            ],
            [
                'application_date' => '2022-07-01',
                'departure_date' => '2022-08-20',
                'day' => '1泊1日',
                'people' => 1,
                'region_id' => 10,
                'cost' => 15000,
                'subsidy' => 8000,
                'coupon' => 4,
                'customer_id' => 10,
                'created_at' =>  now(),
                'updated_at' => now(),
            ],
        ]);
    }
}
